spring :
    application :
        name: finalpj

    mail:
        host: smtp.gmail.com
        default-encoding: utf-8
        port: 587
        username: koraniphoto@gmail.com
        password: onjf xhcu xykj upga
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enabled: true
                        required: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000
        auth-code-expiration-millis: 1800000


    # DB 설정
    datasource:
        url: jdbc:mysql://localhost:3306/ictedu_db
        username: ictedu
        password: 1111
        driver-class-name: com.mysql.cj.jdbc.Driver
    web:
        resources:
            static-locations: file:D:/upload/deal/
            # static-locations: classpath:/static/
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: 1a31dbd4bb00984c5b2d38a62c3d2f0f
                        client-secret: VCIUYRu9VtaTVcOqRJ5DCMEqFvOlGyli
                        redirect-uri: http://localhost:8080/login/oauth2/code/kakao
                        authorization-grant-type: authorization_code
                        client-authentication-method: client_secret_post
                        client-name: Kakao
                        scope:
                            - profile_nickname
                            - profile_image
                            - account_email
                    naver:
                        client-id: JArbJQzekN3B9KzvZp4b
                        client-secret: wdKyUNJCaE
                        redirect-uri: http://localhost:8080/login/oauth2/code/naver
                        authorization-grant-type: authorization_code
                        client-name: Naver
                        scope:
                            - name
                            - email
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
                            
# 파일 업로드 기능에서 파일이 저장될 물리적 경로를 명시
file:
    upload-dir: D:/upload/deal
    
server:
    port: 8080
    servlet:
        context-path: /
        session:
            timeout: 1800
        

# mapper 연결
mybatis:
    mapper-locations: mapper/*.xml
    
    # VO Aliasing
    type-aliases-package: com.ict.finalpj

# 비밀키 사용 (길이 : 32byte)
jwt:
    secret: "abcdABCD1234qwerQWER5678zxcvZXCV9876asdfASDF4321poiuPOIU"  # Base64로 인코딩된 32바이트 이상의 문자열
    expiration: 86400000  # 24시간

